apiVersion: storage.halo.run/v1alpha1
kind: PolicyTemplate
metadata:
  name: alist
spec:
  displayName: Alist 存储
  settingName: alist-policy-template-setting
---
apiVersion: v1alpha1
kind: Setting
metadata:
  name: alist-policy-template-setting
spec:
  forms:
    - group: default
      formSchema:
        - $formkit: verificationForm
          action: "/apis/alist.halo.run/v1alpha1/policies/s3/validation"
          label: Alist 存储验证
          children:
            - $formkit: select
              name: endpointProtocol
              label: 访问协议
              options:
                - label: HTTPS
                  value: https
                - label: HTTP
                  value: http
              validation: required
            - $formkit: text
              name: endpoint
              label: 链接
              placeholder: 请填写 Alist 站点链接
              validation: required
              help: 协议头请在上方设置，此处无需以"http://"或"https://"开头，系统会自动拼接
            - $formkit: password
              name: accessKey
              label: 用户名
              placeholder: 用户名
              validation: required
            - $formkit: password
              name: accessSecret
              label: 密码
              placeholder: 密码
              validation: required
            - $formkit: text
              name: location
              label: 上传目录
              placeholder: 如不填写，则默认上传到根目录
            - $formkit: select
              name: randomFilenameMode
              label: 上传时重命名文件方式
              options:
                - label: 保留原文件名
                  value: none
                - label: 自定义（请在下方输入自定义模板）
                  value: custom
                - label: 使用UUID
                  value: uuid
                - label: 使用毫秒时间戳
                  value: timestampMs
                - label: 使用原文件名 + 随机字母
                  value: withString
                - label: 使用日期 + 随机字母
                  value: dateWithString
                - label: 使用日期时间 + 随机字母
                  value: datetimeWithString
                - label: 使用随机字母
                  value: string
              validation: required
            - $formkit: number
              name: randomStringLength
              key: randomStringLength
              label: 随机字母长度
              min: 4
              max: 16
              if: "$randomFilenameMode == 'dateWithString' || $randomFilenameMode == 'datetimeWithString' || $randomFilenameMode == 'withString' || $randomFilenameMode == 'string'"
              help: 支持4~16位, 默认为8位
            - $formkit: text
              name: customTemplate
              key: customTemplate
              label: 自定义文件名模板
              if: "$randomFilenameMode == 'custom'"
              value: "${origin-filename}"
              help: 支持的占位符请查阅：https://github.com/Anyexyz/plugin-alist#自定义文件名模板
            - $formkit: select
              name: duplicateFilenameHandling
              label: 重复文件名处理方式
              options:
                - label: 加随机字母数字后缀
                  value: randomAlphanumeric
                - label: 加随机字母后缀
                  value: randomAlphabetic
                - label: 报错不上传
                  value: exception
              validation: required