apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-alist-link
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      [ "role-template-manage-attachments" ]
    rbac.authorization.halo.run/module: "S3 Attachments Management"
    rbac.authorization.halo.run/display-name: "S3 Link"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:alist:link"]
rules:
  - apiGroups: [ "alist.halo.run" ]
    resources: [ "policies" ]
    resourceNames: [ "s3" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "alist.halo.run" ]
    resources: [ "objects" ]
    verbs: [ "get", "list" ]
  - nonResourceURLs: ["/apis/alist.halo.run/v1alpha1/attachments/link"]
    verbs: [ "create" ]
---
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-alist-unlink
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      [ "role-template-manage-attachments" ]
    rbac.authorization.halo.run/module: "S3 Attachments Management"
    rbac.authorization.halo.run/display-name: "S3 UnLink"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:alist:unlink"]
rules:
  - apiGroups: [ "alist.halo.run" ]
    resources: [ "attachments" ]
    verbs: [ "delete" ]
---
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-alist-policy-config-validation
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
    rbac.authorization.halo.run/aggregate-to-role-template-manage-configmaps: "true"
rules:
  - apiGroups: ["alist.halo.run"]
    resources: ["policies/validation"]
    resourceNames: ["s3"]
    verbs: [ "create" ]
